services:
  - type: web
    name: weapon-api
    env: python
    runtime: python-3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
